"""auto_full_schema

Revision ID: c70493df5bc0
Revises: 
Create Date: 2025-11-05 19:16:17.179420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c70493df5bc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenants_active_tier', 'tenants', ['active', 'tier'], unique=False)
    op.create_index(op.f('ix_tenants_active'), 'tenants', ['active'], unique=False)
    op.create_index(op.f('ix_tenants_cnpj'), 'tenants', ['cnpj'], unique=True)
    op.create_index(op.f('ix_tenants_tier'), 'tenants', ['tier'], unique=False)
    op.create_table('acquirer_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('acquirer', sa.String(length=50), nullable=False),
    sa.Column('nsu', sa.String(length=50), nullable=False),
    sa.Column('authorization_code', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('transaction_time', sa.String(length=8), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_last_4', sa.String(length=4), nullable=True),
    sa.Column('mdr_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('mdr_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('installment_current', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_nsu_trgm', 'acquirer_transactions', ['nsu'], unique=False, postgresql_using='gin', postgresql_ops={'nsu': 'gin_trgm_ops'})
    op.create_index('idx_transactions_tenant_acquirer', 'acquirer_transactions', ['tenant_id', 'acquirer'], unique=False)
    op.create_index('idx_transactions_tenant_date', 'acquirer_transactions', ['tenant_id', 'transaction_date'], unique=False)
    op.create_index('idx_transactions_tenant_settlement', 'acquirer_transactions', ['tenant_id', 'settlement_date'], unique=False)
    op.create_index(op.f('ix_acquirer_transactions_acquirer'), 'acquirer_transactions', ['acquirer'], unique=False)
    op.create_index(op.f('ix_acquirer_transactions_nsu'), 'acquirer_transactions', ['nsu'], unique=False)
    op.create_index(op.f('ix_acquirer_transactions_settlement_date'), 'acquirer_transactions', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_acquirer_transactions_tenant_id'), 'acquirer_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_acquirer_transactions_transaction_date'), 'acquirer_transactions', ['transaction_date'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('alert_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_history_rule', 'alert_history', ['rule_id', 'triggered_at'], unique=False)
    op.create_index('idx_alert_history_tenant', 'alert_history', ['tenant_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_history_rule_id'), 'alert_history', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_tenant_id'), 'alert_history', ['tenant_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.String(length=64), nullable=False),
    sa.Column('bank_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('description_user_friendly', sa.Text(), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bank_transactions_fitid', 'bank_transactions', ['tenant_id', 'bank_account_id', 'bank_transaction_id'], unique=True)
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_transaction_id'), 'bank_transactions', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_is_reconciled'), 'bank_transactions', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_bank_transactions_tenant_id'), 'bank_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_table('import_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('acquirer', sa.String(length=50), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('days_to_import', sa.Integer(), nullable=False),
    sa.Column('credential_hint', sa.String(length=120), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_schedules_active', 'import_schedules', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_import_schedules_tenant', 'import_schedules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_import_schedules_is_active'), 'import_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_import_schedules_tenant_id'), 'import_schedules', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_tenant_created', 'notifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_unread', 'notifications', ['tenant_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nsu', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('authorization_code', sa.String(length=50), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_nsu_trgm', 'sales', ['nsu'], unique=False, postgresql_using='gin', postgresql_ops={'nsu': 'gin_trgm_ops'})
    op.create_index('idx_sales_tenant_date', 'sales', ['tenant_id', 'date'], unique=False)
    op.create_index('idx_sales_tenant_nsu', 'sales', ['tenant_id', 'nsu'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_nsu'), 'sales', ['nsu'], unique=False)
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["user"]\'::jsonb'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_tenant_email', 'users', ['tenant_id', 'email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('bank_reconciliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('acquirer_transaction_id', sa.UUID(), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acquirer_transaction_id'], ['acquirer_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bank_reconciliations_tenant', 'bank_reconciliations', ['tenant_id', 'matched_at'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_acquirer_transaction_id'), 'bank_reconciliations', ['acquirer_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_bank_transaction_id'), 'bank_reconciliations', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_tenant_id'), 'bank_reconciliations', ['tenant_id'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validated_by', sa.String(length=100), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['acquirer_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_matches_confidence', 'reconciliation_matches', ['confidence'], unique=False)
    op.create_index('idx_matches_tenant_validated', 'reconciliation_matches', ['tenant_id', 'validated'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_sale_id'), 'reconciliation_matches', ['sale_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_tenant_id'), 'reconciliation_matches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_transaction_id'), 'reconciliation_matches', ['transaction_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['acquirer_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_settlements_expected_date', 'settlements', ['expected_date'], unique=False)
    op.create_index('idx_settlements_tenant_status', 'settlements', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_settlements_expected_date'), 'settlements', ['expected_date'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_index(op.f('ix_settlements_tenant_id'), 'settlements', ['tenant_id'], unique=False)
    op.create_table('divergences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('divergence_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['reconciliation_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_divergences_detected_at', 'divergences', ['detected_at'], unique=False)
    op.create_index('idx_divergences_tenant_severity', 'divergences', ['tenant_id', 'severity'], unique=False)
    op.create_index('idx_divergences_tenant_status', 'divergences', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_divergences_divergence_type'), 'divergences', ['divergence_type'], unique=False)
    op.create_index(op.f('ix_divergences_severity'), 'divergences', ['severity'], unique=False)
    op.create_index(op.f('ix_divergences_status'), 'divergences', ['status'], unique=False)
    op.create_index(op.f('ix_divergences_tenant_id'), 'divergences', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divergences_tenant_id'), table_name='divergences')
    op.drop_index(op.f('ix_divergences_status'), table_name='divergences')
    op.drop_index(op.f('ix_divergences_severity'), table_name='divergences')
    op.drop_index(op.f('ix_divergences_divergence_type'), table_name='divergences')
    op.drop_index('idx_divergences_tenant_status', table_name='divergences')
    op.drop_index('idx_divergences_tenant_severity', table_name='divergences')
    op.drop_index('idx_divergences_detected_at', table_name='divergences')
    op.drop_table('divergences')
    op.drop_index(op.f('ix_settlements_tenant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_expected_date'), table_name='settlements')
    op.drop_index('idx_settlements_tenant_status', table_name='settlements')
    op.drop_index('idx_settlements_expected_date', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_reconciliation_matches_transaction_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_tenant_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_sale_id'), table_name='reconciliation_matches')
    op.drop_index('idx_matches_tenant_validated', table_name='reconciliation_matches')
    op.drop_index('idx_matches_confidence', table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index(op.f('ix_bank_reconciliations_tenant_id'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_bank_transaction_id'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_acquirer_transaction_id'), table_name='bank_reconciliations')
    op.drop_index('idx_bank_reconciliations_tenant', table_name='bank_reconciliations')
    op.drop_table('bank_reconciliations')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_tenant_email', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_nsu'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index('idx_sales_tenant_nsu', table_name='sales')
    op.drop_index('idx_sales_tenant_date', table_name='sales')
    op.drop_index('idx_sales_nsu_trgm', table_name='sales', postgresql_using='gin', postgresql_ops={'nsu': 'gin_trgm_ops'})
    op.drop_table('sales')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications')
    op.drop_index('idx_notifications_tenant_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_import_schedules_tenant_id'), table_name='import_schedules')
    op.drop_index(op.f('ix_import_schedules_is_active'), table_name='import_schedules')
    op.drop_index('idx_import_schedules_tenant', table_name='import_schedules')
    op.drop_index('idx_import_schedules_active', table_name='import_schedules')
    op.drop_table('import_schedules')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_tenant_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_is_reconciled'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_transaction_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_index('idx_bank_transactions_fitid', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_alert_history_tenant_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_rule_id'), table_name='alert_history')
    op.drop_index('idx_alert_history_tenant', table_name='alert_history')
    op.drop_index('idx_alert_history_rule', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_acquirer_transactions_transaction_date'), table_name='acquirer_transactions')
    op.drop_index(op.f('ix_acquirer_transactions_tenant_id'), table_name='acquirer_transactions')
    op.drop_index(op.f('ix_acquirer_transactions_settlement_date'), table_name='acquirer_transactions')
    op.drop_index(op.f('ix_acquirer_transactions_nsu'), table_name='acquirer_transactions')
    op.drop_index(op.f('ix_acquirer_transactions_acquirer'), table_name='acquirer_transactions')
    op.drop_index('idx_transactions_tenant_settlement', table_name='acquirer_transactions')
    op.drop_index('idx_transactions_tenant_date', table_name='acquirer_transactions')
    op.drop_index('idx_transactions_tenant_acquirer', table_name='acquirer_transactions')
    op.drop_index('idx_transactions_nsu_trgm', table_name='acquirer_transactions', postgresql_using='gin', postgresql_ops={'nsu': 'gin_trgm_ops'})
    op.drop_table('acquirer_transactions')
    op.drop_index(op.f('ix_tenants_tier'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_cnpj'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_active'), table_name='tenants')
    op.drop_index('idx_tenants_active_tier', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
