"""Incident response plan orchestration utilities."""

from __future__ import annotations

import json
import secrets
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Awaitable, Callable, Dict, List, Optional, Protocol

import structlog

logger = structlog.get_logger(__name__)


class IncidentSeverity(str, Enum):
    """Supported levels of severity for security incidents."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IncidentType(str, Enum):
    """Types of incidents monitored by the platform."""

    DATA_BREACH = "data_breach"
    UNAUTHORIZED_ACCESS = "unauthorized_access"
    DENIAL_OF_SERVICE = "denial_of_service"
    MALWARE = "malware"
    INSIDER_THREAT = "insider_threat"
    VULNERABILITY = "vulnerability"


class AuditEventType(str, Enum):
    """Audit event types generated by the incident response workflow."""

    SECURITY_ALERT = "security_alert"


class DatabaseProtocol(Protocol):
    """Minimal async database contract used by the manager."""

    async def execute(self, query: str, *args: Any) -> Any:
        ...

    async def fetchrow(self, query: str, *args: Any) -> Optional[Dict[str, Any]]:
        ...


class AuditLogger(Protocol):
    """Contract for audit loggers."""

    async def log_event(
        self, event_type: AuditEventType, actor_id: str, details: Dict[str, Any]
    ) -> None:
        ...


SlackNotifier = Callable[[str, str, Optional[str]], Awaitable[None]]
PagerDutyTrigger = Callable[[str, str], Awaitable[None]]
EmailSender = Callable[[str, str, str], Awaitable[None]]


@dataclass(slots=True)
class IncidentResponseSettings:
    """Configuration values used by the incident response manager."""

    slack_security_webhook: Optional[str] = None
    pagerduty_integration_key: Optional[str] = None
    security_team_email: Optional[str] = None


class IncidentResponseManager:
    """Manage security incidents end-to-end."""

    def __init__(
        self,
        database: DatabaseProtocol,
        audit_logger: AuditLogger,
        settings: IncidentResponseSettings,
        slack_notifier: Optional[SlackNotifier] = None,
        pagerduty_trigger: Optional[PagerDutyTrigger] = None,
        email_sender: Optional[EmailSender] = None,
    ) -> None:
        self._db = database
        self._audit_logger = audit_logger
        self._settings = settings
        self._slack_notifier = slack_notifier or _log_only_slack_notifier
        self._pagerduty_trigger = pagerduty_trigger or _log_only_pagerduty_trigger
        self._email_sender = email_sender or _log_only_email_sender

    async def report_incident(
        self,
        incident_type: IncidentType,
        severity: IncidentSeverity,
        description: str,
        detected_by: str,
        affected_systems: Optional[List[str]] = None,
    ) -> str:
        """Report and persist a new security incident."""

        incident_id = _generate_incident_id()

        await self._db.execute(
            """
            INSERT INTO security_incidents (
                id, incident_type, severity, description,
                detected_by, affected_systems, detected_at, status
            ) VALUES ($1, $2, $3, $4, $5, $6, NOW(), 'open')
            """,
            incident_id,
            incident_type.value,
            severity.value,
            description,
            detected_by,
            json.dumps(affected_systems or []),
        )

        if severity == IncidentSeverity.CRITICAL:
            await self._critical_response(incident_id, incident_type)
        elif severity == IncidentSeverity.HIGH:
            await self._high_response(incident_id, incident_type)

        await self._audit_logger.log_event(
            event_type=AuditEventType.SECURITY_ALERT,
            actor_id="system",
            details={
                "incident_id": incident_id,
                "type": incident_type.value,
                "severity": severity.value,
            },
        )

        return incident_id

    async def _critical_response(
        self, incident_id: str, incident_type: IncidentType
    ) -> None:
        await self._alert_security_team(incident_id, "CRITICAL")

        if incident_type == IncidentType.DATA_BREACH:
            await self._isolate_systems(incident_id)

        await self._enable_enhanced_monitoring()
        await self._create_incident_channel(incident_id)

    async def _high_response(
        self, incident_id: str, incident_type: IncidentType
    ) -> None:
        await self._alert_security_team(incident_id, "HIGH")
        await self._increase_logging()
        await self._review_related_systems(incident_id)

    async def _alert_security_team(self, incident_id: str, severity: str) -> None:
        incident = await self._db.fetchrow(
            "SELECT * FROM security_incidents WHERE id = $1", incident_id
        )

        if incident is None:
            logger.warning(
                "incident_not_found_during_alert", incident_id=incident_id, severity=severity
            )
            return

        incident_data = dict(incident)
        message = (
            "\n".join(
                [
                    "🚨 Security Incident: {severity}",
                    "",
                    "Incident ID: {incident_id}",
                    "Type: {incident_type}",
                    "Severity: {severity}",
                    "Description: {description}",
                    "Detected: {detected_at}",
                    "Dashboard: https://buildtovalue.example.com/security/incidents/{incident_id}",
                ]
            )
        ).format(
            severity=severity,
            incident_id=incident_id,
            incident_type=incident_data.get("incident_type", "unknown"),
            description=incident_data.get("description", ""),
            detected_at=incident_data.get("detected_at", datetime.utcnow()),
        )

        if self._settings.slack_security_webhook:
            await self._slack_notifier(
                self._settings.slack_security_webhook, message, channel="#security-alerts"
            )

        if severity == "CRITICAL" and self._settings.pagerduty_integration_key:
            await self._pagerduty_trigger(incident_id, message)

        if self._settings.security_team_email:
            await self._email_sender(
                self._settings.security_team_email,
                f"[{severity}] Security Incident: {incident_id}",
                message,
            )

    async def _isolate_systems(self, incident_id: str) -> None:
        logger.warning("isolating_systems", incident_id=incident_id)

        incident = await self._db.fetchrow(
            "SELECT affected_systems FROM security_incidents WHERE id = $1", incident_id
        )

        if not incident:
            logger.warning("incident_not_found_for_isolation", incident_id=incident_id)
            return

        incident_data = dict(incident)
        affected = json.loads(incident_data.get("affected_systems") or "[]")

        for system in affected:
            await self._block_system(system)
            await self._revoke_system_keys(system)

        await self._audit_logger.log_event(
            event_type=AuditEventType.SECURITY_ALERT,
            actor_id="system",
            details={
                "action": "systems_isolated",
                "incident_id": incident_id,
                "systems": affected,
            },
        )

    async def _increase_logging(self) -> None:
        logger.info("increasing_security_logging")

    async def _review_related_systems(self, incident_id: str) -> None:
        logger.info("reviewing_related_systems", incident_id=incident_id)

    async def _enable_enhanced_monitoring(self) -> None:
        logger.info("enabling_enhanced_monitoring")

    async def _create_incident_channel(self, incident_id: str) -> None:
        logger.info("creating_incident_war_room", incident_id=incident_id)

    async def _block_system(self, system: str) -> None:
        logger.warning("blocking_system", system=system)

    async def _revoke_system_keys(self, system: str) -> None:
        logger.warning("revoking_system_keys", system=system)

    async def update_incident(
        self,
        incident_id: str,
        status: Optional[str] = None,
        resolution: Optional[str] = None,
        lessons_learned: Optional[str] = None,
    ) -> None:
        updates: List[str] = []
        params: List[Any] = []
        index = 1

        if status:
            updates.append(f"status = ${index}")
            params.append(status)
            index += 1
            if status == "resolved":
                updates.append("resolved_at = NOW()")

        if resolution:
            updates.append(f"resolution = ${index}")
            params.append(resolution)
            index += 1

        if lessons_learned:
            updates.append(f"lessons_learned = ${index}")
            params.append(lessons_learned)
            index += 1

        if not updates:
            logger.info("incident_update_noop", incident_id=incident_id)
            return

        query = f"UPDATE security_incidents SET {', '.join(updates)} WHERE id = ${index}"
        params.append(incident_id)

        await self._db.execute(query, *params)

        await self._audit_logger.log_event(
            event_type=AuditEventType.SECURITY_ALERT,
            actor_id="system",
            details={
                "incident_id": incident_id,
                "status": status,
                "resolution": resolution,
                "lessons_learned": lessons_learned,
            },
        )


def _generate_incident_id() -> str:
    return f"INC-{datetime.utcnow().strftime('%Y%m%d')}-{secrets.token_hex(4).upper()}"


async def _log_only_slack_notifier(
    webhook: str, message: str, channel: Optional[str] = None
) -> None:
    logger.info(
        "slack_notification", webhook=webhook, channel=channel or "default", message=message
    )


async def _log_only_pagerduty_trigger(incident_id: str, message: str) -> None:
    logger.info("pagerduty_alert", incident_id=incident_id, message=message)


async def _log_only_email_sender(to: str, subject: str, body: str) -> None:
    logger.info("email_notification", to=to, subject=subject, body=body)


__all__ = [
    "AuditEventType",
    "IncidentResponseManager",
    "IncidentResponseSettings",
    "IncidentSeverity",
    "IncidentType",
]
